In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob
import pyarrow as pa

In [3]:
glob.glob('D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail/transactions_*.csv')

['D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200607.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200608.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200609.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200610.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200611.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200612.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200613.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200614.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200615.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200616.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200617.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200618.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200619.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200620.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200621.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200622.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200623.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200624.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200625.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200626.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200627.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200628.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200629.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200630.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200631.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200632.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200633.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200634.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200635.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200636.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200637.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200638.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200639.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200640.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200641.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200642.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200643.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200644.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200645.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200646.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200647.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200648.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200649.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200650.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200651.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200652.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200701.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200702.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200703.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200704.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200705.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200706.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200707.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200708.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200709.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200710.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200711.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200712.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200713.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200714.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200715.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200716.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200717.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200718.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200719.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200720.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200721.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200722.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200723.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200724.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200725.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200726.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200727.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200728.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200729.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200730.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200731.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200732.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200733.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200734.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200735.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200736.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200737.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200738.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200739.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200740.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200741.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200742.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200743.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200744.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200745.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200746.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200747.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200748.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200749.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200750.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200751.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200752.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200801.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200802.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200803.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200804.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200805.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200806.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200807.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200808.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200809.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200810.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200811.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200812.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200813.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200814.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200815.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200816.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200817.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200818.csv',
 'D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\\transactions_200819.csv']

In [4]:
all_dfs=[]

for df in glob.glob('D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail/transactions_*.csv'):
    print(f'Loading {df}')
    new_df=pd.read_csv(df)

    all_dfs.append(new_df)

Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200607.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200608.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200609.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200610.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200611.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200612.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200613.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200614.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200615.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200616.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200617.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200618.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200619.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200620.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200621.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200622.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200623.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200624.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200625.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200626.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200627.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200628.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200629.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200630.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200631.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200632.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200633.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200634.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200635.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200636.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200637.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200638.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200639.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200640.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200641.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200642.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200643.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200644.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200645.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200646.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200647.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200648.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200649.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200650.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200651.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200652.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200701.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200702.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200703.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200704.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200705.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200706.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200707.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200708.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200709.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200710.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200711.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200712.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200713.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200714.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200715.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200716.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200717.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200718.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200719.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200720.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200721.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200722.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200723.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200724.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200725.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200726.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200727.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200728.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200729.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200730.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200731.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200732.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200733.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200734.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200735.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200736.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200737.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200738.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200739.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200740.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200741.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200742.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200743.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200744.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200745.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200746.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200747.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200748.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200749.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200750.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200751.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200752.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200801.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200802.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200803.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200804.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200805.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200806.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200807.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200808.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200809.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200810.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200811.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200812.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200813.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200814.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200815.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200816.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200817.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200818.csv
Loading D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail\transactions_200819.csv

In [5]:
df=pd.concat(all_dfs)
df.to_parquet('dunnhumby_clean.parquet', compression='snappy')

<class 'pandas.DataFrame'>
Index: 31057875 entries, 0 to 270685
Data columns (total 24 columns):
 #   Column                    Dtype
---  ------                    -----
 0   SHOP_WEEK                 int64
 1   SHOP_DATE                 int64
 2   SHOP_WEEKDAY              int64
 3   SHOP_HOUR                 int64
 4   QUANTITY                  int64
 5   SFNND                     float64
 6   PROD_CODE                 str
 7   PROD_CODE_10              str
 8   PROD_CODE_20              str
 9   PROD_CODE_30              str
 10  PROD_CODE_40              str
 11  CUST_CODE                 str
 12  seg_1                     str
 13  seg_2                     str
 14  BASKET_ID                 float64
 15  BASKET_SIZE               str
 16  BASKET_PRICE_SENSITIVITY  str
 17  BASKET_TYFN               str
 18  BASKET_DOMINANT_MISSION   str
 19  STORE_CODE                str
 20  STORE_FORMAT              str
 21  STORE_REGION              str
 22  SPEND                     float64
 23  BASKET_TYPE               str
dtypes: float64(3), int64(5), str(16)
memory usage: 8.2 GB

None

,SHOP_WEEK,SHOP_DATE,SHOP_WEEKDAY,SHOP_HOUR,QUANTITY,SFNND,PROD_CODE,PROD_CODE_10,PROD_CODE_20,PROD_CODE_30,...,BASKET_ID,BASKET_SIZE,BASKET_PRICE_SENSITIVITY,BASKET_TYFN,BASKET_DOMINANT_MISSION,STORE_CODE,STORE_FORMAT,STORE_REGION,SPEND,BASKET_TYPE
0,200607,20060411,3,16,1,1.05,PRD0900011,CL00033,DEP00008,G00004,...,9.941000e+14,L,UM,Top Up,Fresh,STORE00001,LS,E02,NaN,NaN
1,200607,20060411,3,19,3,1.65,PRD0900035,CL00113,DEP00040,G00011,...,9.941000e+14,L,MM,Full Shop,Mixed,STORE00001,LS,E02,NaN,NaN
2,200607,20060414,6,21,1,0.71,PRD0900043,CL00148,DEP00052,G00015,...,9.941000e+14,L,LA,Top Up,Mixed,STORE00001,LS,E02,NaN,NaN
3,200607,20060414,6,14,1,0.46,PRD0900057,CL00107,DEP00037,G00010,...,9.941000e+14,L,LA,Full Shop,Fresh,STORE00001,LS,E02,NaN,NaN
4,200607,20060411,3,16,1,1.87,PRD0900058,CL00020,DEP00005,G00003,...,9.941000e+14,L,UM,Top Up,Fresh,STORE00001,LS,E02,NaN,NaN

Index(['SHOP_WEEK', 'SHOP_DATE', 'SHOP_WEEKDAY', 'SHOP_HOUR', 'QUANTITY',
       'SFNND', 'PROD_CODE', 'PROD_CODE_10', 'PROD_CODE_20', 'PROD_CODE_30',
       'PROD_CODE_40', 'CUST_CODE', 'seg_1', 'seg_2', 'BASKET_ID',
       'BASKET_SIZE', 'BASKET_PRICE_SENSITIVITY', 'BASKET_TYFN',
       'BASKET_DOMINANT_MISSION', 'STORE_CODE', 'STORE_FORMAT', 'STORE_REGION',
       'SPEND', 'BASKET_TYPE'],
      dtype='str')

In [3]:
df=pd.read_parquet('dunnhumby_clean.parquet')
display(df.info(), df.head(5), df.columns)

<class 'pandas.DataFrame'>
Index: 31057875 entries, 0 to 270685
Data columns (total 24 columns):
 #   Column                    Dtype
---  ------                    -----
 0   SHOP_WEEK                 int64
 1   SHOP_DATE                 int64
 2   SHOP_WEEKDAY              int64
 3   SHOP_HOUR                 int64
 4   QUANTITY                  int64
 5   SFNND                     float64
 6   PROD_CODE                 str
 7   PROD_CODE_10              str
 8   PROD_CODE_20              str
 9   PROD_CODE_30              str
 10  PROD_CODE_40              str
 11  CUST_CODE                 str
 12  seg_1                     str
 13  seg_2                     str
 14  BASKET_ID                 float64
 15  BASKET_SIZE               str
 16  BASKET_PRICE_SENSITIVITY  str
 17  BASKET_TYFN               str
 18  BASKET_DOMINANT_MISSION   str
 19  STORE_CODE                str
 20  STORE_FORMAT              str
 21  STORE_REGION              str
 22  SPEND                     float64
 23  BASKET_TYPE               str
dtypes: float64(3), int64(5), str(16)
memory usage: 8.2 GB

None

,SHOP_WEEK,SHOP_DATE,SHOP_WEEKDAY,SHOP_HOUR,QUANTITY,SFNND,PROD_CODE,PROD_CODE_10,PROD_CODE_20,PROD_CODE_30,...,BASKET_ID,BASKET_SIZE,BASKET_PRICE_SENSITIVITY,BASKET_TYFN,BASKET_DOMINANT_MISSION,STORE_CODE,STORE_FORMAT,STORE_REGION,SPEND,BASKET_TYPE
0,200607,20060411,3,16,1,1.05,PRD0900011,CL00033,DEP00008,G00004,...,9.941000e+14,L,UM,Top Up,Fresh,STORE00001,LS,E02,NaN,NaN
1,200607,20060411,3,19,3,1.65,PRD0900035,CL00113,DEP00040,G00011,...,9.941000e+14,L,MM,Full Shop,Mixed,STORE00001,LS,E02,NaN,NaN
2,200607,20060414,6,21,1,0.71,PRD0900043,CL00148,DEP00052,G00015,...,9.941000e+14,L,LA,Top Up,Mixed,STORE00001,LS,E02,NaN,NaN
3,200607,20060414,6,14,1,0.46,PRD0900057,CL00107,DEP00037,G00010,...,9.941000e+14,L,LA,Full Shop,Fresh,STORE00001,LS,E02,NaN,NaN
4,200607,20060411,3,16,1,1.87,PRD0900058,CL00020,DEP00005,G00003,...,9.941000e+14,L,UM,Top Up,Fresh,STORE00001,LS,E02,NaN,NaN

Index(['SHOP_WEEK', 'SHOP_DATE', 'SHOP_WEEKDAY', 'SHOP_HOUR', 'QUANTITY',
       'SFNND', 'PROD_CODE', 'PROD_CODE_10', 'PROD_CODE_20', 'PROD_CODE_30',
       'PROD_CODE_40', 'CUST_CODE', 'seg_1', 'seg_2', 'BASKET_ID',
       'BASKET_SIZE', 'BASKET_PRICE_SENSITIVITY', 'BASKET_TYFN',
       'BASKET_DOMINANT_MISSION', 'STORE_CODE', 'STORE_FORMAT', 'STORE_REGION',
       'SPEND', 'BASKET_TYPE'],
      dtype='str')

In [4]:
df['SPEND']

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
          ...
270681    0.39
270682    5.07
270683    0.38
270684    0.41
270685    0.93
Name: SPEND, Length: 31057875, dtype: float64

In [5]:
print(df['SPEND'].notna().sum(), df['SFNND'].notna().sum())
print((df['SPEND'].notna() & df['SFNND'].notna()).sum())

30807329 250546
0

In [6]:
df['SPEND']=df['SPEND'].fillna(df['SFNND'])
df['BASKET_TYPE']=df['BASKET_TYPE'].fillna(df['BASKET_TYFN'])

df = df.drop(columns=['SFNND', 'BASKET_TYFN'])

In [7]:
df

,SHOP_WEEK,SHOP_DATE,SHOP_WEEKDAY,SHOP_HOUR,QUANTITY,PROD_CODE,PROD_CODE_10,PROD_CODE_20,PROD_CODE_30,PROD_CODE_40,...,seg_2,BASKET_ID,BASKET_SIZE,BASKET_PRICE_SENSITIVITY,BASKET_DOMINANT_MISSION,STORE_CODE,STORE_FORMAT,STORE_REGION,SPEND,BASKET_TYPE
0,200607,20060411,3,16,1,PRD0900011,CL00033,DEP00008,G00004,D00002,...,NaN,9.941000e+14,L,UM,Fresh,STORE00001,LS,E02,1.05,Top Up
1,200607,20060411,3,19,3,PRD0900035,CL00113,DEP00040,G00011,D00003,...,CZ,9.941000e+14,L,MM,Mixed,STORE00001,LS,E02,1.65,Full Shop
2,200607,20060414,6,21,1,PRD0900043,CL00148,DEP00052,G00015,D00003,...,NaN,9.941000e+14,L,LA,Mixed,STORE00001,LS,E02,0.71,Top Up
3,200607,20060414,6,14,1,PRD0900057,CL00107,DEP00037,G00010,D00003,...,FN,9.941000e+14,L,LA,Fresh,STORE00001,LS,E02,0.46,Full Shop
4,200607,20060411,3,16,1,PRD0900058,CL00020,DEP00005,G00003,D00001,...,NaN,9.941000e+14,L,UM,Fresh,STORE00001,LS,E02,1.87,Top Up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270681,200819,20080703,5,15,3,PRD0902428,CL00222,DEP00076,G00023,D00005,...,NaN,9.941117e+14,L,UM,Mixed,STORE01062,SS,E02,0.39,Full Shop
270682,200819,20080701,3,14,3,PRD0902348,CL00092,DEP00027,G00008,D00002,...,DI,9.941117e+14,L,LA,Mixed,STORE01062,SS,E02,5.07,Top Up
270683,200819,20080701,3,14,1,PRD0904799,CL00092,DEP00027,G00008,D00002,...,DI,9.941117e+14,L,LA,Mixed,STORE01062,SS,E02,0.38,Top Up
270684,200819,20080705,7,13,1,PRD0901943,CL00043,DEP00011,G00004,D00002,...,NaN,9.941117e+14,M,UM,Fresh,STORE01062,SS,E02,0.41,Top Up
270685,200819,20080705,7,13,1,PRD0903966,CL00068,DEP00019,G00007,D00002,...,NaN,9.941117e+14,M,UM,Fresh,STORE01062,SS,E02,0.93,Top Up

In [11]:
df['SHOP_WEEK']=df['SHOP_WEEK'].astype(str)
df['SHOP_DATE']=pd.to_datetime(df['SHOP_DATE'], format='%Y%m%d')

In [14]:
df[df.duplicated()]

,SHOP_WEEK,SHOP_DATE,SHOP_WEEKDAY,SHOP_HOUR,QUANTITY,PROD_CODE,PROD_CODE_10,PROD_CODE_20,PROD_CODE_30,PROD_CODE_40,...,seg_2,BASKET_ID,BASKET_SIZE,BASKET_PRICE_SENSITIVITY,BASKET_DOMINANT_MISSION,STORE_CODE,STORE_FORMAT,STORE_REGION,SPEND,BASKET_TYPE
25131,200607,2006-04-14,6,18,1,PRD0900317,CL00160,DEP00054,G00016,D00003,...,NaN,9.941000e+14,L,MM,Fresh,STORE00291,LS,N02,2.53,Top Up
42312,200607,2006-04-14,6,15,1,PRD0904044,CL00014,DEP00004,G00003,D00001,...,BU,9.941000e+14,S,LA,Fresh,STORE00494,MS,E01,0.56,Small Shop
89564,200607,2006-04-10,2,16,3,PRD0902817,CL00225,DEP00077,G00024,D00006,...,NaN,9.941000e+14,M,XX,XX,STORE01061,LS,W02,12.24,XX
111942,200607,2006-04-15,7,18,1,PRD0900986,CL00151,DEP00052,G00015,D00003,...,BU,9.941000e+14,S,LA,Grocery,STORE01316,LS,S01,1.22,Small Shop
139957,200607,2006-04-12,4,21,1,PRD0901331,CL00238,DEP00084,G00028,D00008,...,CZ,9.941000e+14,M,MM,Grocery,STORE01616,LS,N02,2.61,Small Shop
140145,200607,2006-04-12,4,21,3,PRD0903115,CL00149,DEP00052,G00015,D00003,...,CZ,9.941000e+14,M,MM,Grocery,STORE01616,LS,N02,1.53,Small Shop
143565,200607,2006-04-15,7,21,1,PRD0900466,CL00049,DEP00012,G00004,D00002,...,NaN,9.941000e+14,M,UM,Fresh,STORE01664,SS,W01,0.70,Small Shop
151062,200607,2006-04-14,6,11,3,PRD0904335,CL00020,DEP00005,G00003,D00001,...,BU,9.941000e+14,M,MM,Fresh,STORE01735,MS,W03,2.25,Small Shop
151307,200607,2006-04-14,6,14,1,PRD0901329,CL00154,DEP00052,G00015,D00003,...,BU,9.941000e+14,S,MM,Fresh,STORE01741,LS,S02,0.33,Small Shop
194631,200607,2006-04-12,4,13,3,PRD0900254,CL00001,DEP00001,G00001,D00001,...,EQ,9.941000e+14,L,LA,Mixed,STORE02303,XLS,E03,2.55,Top Up
194668,200607,2006-04-12,4,13,1,PRD0900415,CL00040,DEP00010,G00004,D00002,...,EQ,9.941000e+14,L,LA,Mixed,STORE02303,XLS,E03,0.70,Top Up
194772,200607,2006-04-12,4,13,1,PRD0901108,CL00065,DEP00019,G00007,D00002,...,EQ,9.941000e+14,L,LA,Mixed,STORE02303,XLS,E03,1.24,Top Up
220141,200607,2006-04-14,6,21,3,PRD0900705,CL00088,DEP00025,G00008,D00002,...,AT,9.941000e+14,L,MM,Fresh,STORE02547,LS,E02,3.18,Top Up
230820,200607,2006-04-12,4,8,1,PRD0901887,CL00063,DEP00019,G00007,D00002,...,FN,9.941000e+14,M,MM,Mixed,STORE02696,LS,W02,0.86,Top Up
241377,200607,2006-04-15,7,8,6,PRD0902735,CL00020,DEP00005,G00003,D00001,...,NaN,9.941000e+14,M,MM,Fresh,STORE02804,MS,W02,2.64,Small Shop

In [15]:
df=df.drop_duplicates()

In [16]:
df['BASKET_ID']=df['BASKET_ID'].astype('int64')

In [17]:
df

,SHOP_WEEK,SHOP_DATE,SHOP_WEEKDAY,SHOP_HOUR,QUANTITY,PROD_CODE,PROD_CODE_10,PROD_CODE_20,PROD_CODE_30,PROD_CODE_40,...,seg_2,BASKET_ID,BASKET_SIZE,BASKET_PRICE_SENSITIVITY,BASKET_DOMINANT_MISSION,STORE_CODE,STORE_FORMAT,STORE_REGION,SPEND,BASKET_TYPE
0,200607,2006-04-11,3,16,1,PRD0900011,CL00033,DEP00008,G00004,D00002,...,NaN,994100000000000,L,UM,Fresh,STORE00001,LS,E02,1.05,Top Up
1,200607,2006-04-11,3,19,3,PRD0900035,CL00113,DEP00040,G00011,D00003,...,CZ,994100000000000,L,MM,Mixed,STORE00001,LS,E02,1.65,Full Shop
2,200607,2006-04-14,6,21,1,PRD0900043,CL00148,DEP00052,G00015,D00003,...,NaN,994100000000000,L,LA,Mixed,STORE00001,LS,E02,0.71,Top Up
3,200607,2006-04-14,6,14,1,PRD0900057,CL00107,DEP00037,G00010,D00003,...,FN,994100000000000,L,LA,Fresh,STORE00001,LS,E02,0.46,Full Shop
4,200607,2006-04-11,3,16,1,PRD0900058,CL00020,DEP00005,G00003,D00001,...,NaN,994100000000000,L,UM,Fresh,STORE00001,LS,E02,1.87,Top Up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270681,200819,2008-07-03,5,15,3,PRD0902428,CL00222,DEP00076,G00023,D00005,...,NaN,994111700127061,L,UM,Mixed,STORE01062,SS,E02,0.39,Full Shop
270682,200819,2008-07-01,3,14,3,PRD0902348,CL00092,DEP00027,G00008,D00002,...,DI,994111700733938,L,LA,Mixed,STORE01062,SS,E02,5.07,Top Up
270683,200819,2008-07-01,3,14,1,PRD0904799,CL00092,DEP00027,G00008,D00002,...,DI,994111700733938,L,LA,Mixed,STORE01062,SS,E02,0.38,Top Up
270684,200819,2008-07-05,7,13,1,PRD0901943,CL00043,DEP00011,G00004,D00002,...,NaN,994111700167348,M,UM,Fresh,STORE01062,SS,E02,0.41,Top Up
270685,200819,2008-07-05,7,13,1,PRD0903966,CL00068,DEP00019,G00007,D00002,...,NaN,994111700167348,M,UM,Fresh,STORE01062,SS,E02,0.93,Top Up

In [20]:
weekdays={
    1:'Sunday',
    2:'Monday',
    3:'Tuesday',
    4:'Wednesday',
    5:'Thursday',
    6:'Friday',
    7:'Saturday'
}

df['SHOP_WEEKDAY']=df['SHOP_WEEKDAY'].map(weekdays).astype('str')
df

,SHOP_WEEK,SHOP_DATE,SHOP_WEEKDAY,SHOP_HOUR,QUANTITY,PROD_CODE,PROD_CODE_10,PROD_CODE_20,PROD_CODE_30,PROD_CODE_40,...,seg_2,BASKET_ID,BASKET_SIZE,BASKET_PRICE_SENSITIVITY,BASKET_DOMINANT_MISSION,STORE_CODE,STORE_FORMAT,STORE_REGION,SPEND,BASKET_TYPE
0,200607,2006-04-11,Tuesday,16,1,PRD0900011,CL00033,DEP00008,G00004,D00002,...,NaN,994100000000000,L,UM,Fresh,STORE00001,LS,E02,1.05,Top Up
1,200607,2006-04-11,Tuesday,19,3,PRD0900035,CL00113,DEP00040,G00011,D00003,...,CZ,994100000000000,L,MM,Mixed,STORE00001,LS,E02,1.65,Full Shop
2,200607,2006-04-14,Friday,21,1,PRD0900043,CL00148,DEP00052,G00015,D00003,...,NaN,994100000000000,L,LA,Mixed,STORE00001,LS,E02,0.71,Top Up
3,200607,2006-04-14,Friday,14,1,PRD0900057,CL00107,DEP00037,G00010,D00003,...,FN,994100000000000,L,LA,Fresh,STORE00001,LS,E02,0.46,Full Shop
4,200607,2006-04-11,Tuesday,16,1,PRD0900058,CL00020,DEP00005,G00003,D00001,...,NaN,994100000000000,L,UM,Fresh,STORE00001,LS,E02,1.87,Top Up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270681,200819,2008-07-03,Thursday,15,3,PRD0902428,CL00222,DEP00076,G00023,D00005,...,NaN,994111700127061,L,UM,Mixed,STORE01062,SS,E02,0.39,Full Shop
270682,200819,2008-07-01,Tuesday,14,3,PRD0902348,CL00092,DEP00027,G00008,D00002,...,DI,994111700733938,L,LA,Mixed,STORE01062,SS,E02,5.07,Top Up
270683,200819,2008-07-01,Tuesday,14,1,PRD0904799,CL00092,DEP00027,G00008,D00002,...,DI,994111700733938,L,LA,Mixed,STORE01062,SS,E02,0.38,Top Up
270684,200819,2008-07-05,Saturday,13,1,PRD0901943,CL00043,DEP00011,G00004,D00002,...,NaN,994111700167348,M,UM,Fresh,STORE01062,SS,E02,0.41,Top Up
270685,200819,2008-07-05,Saturday,13,1,PRD0903966,CL00068,DEP00019,G00007,D00002,...,NaN,994111700167348,M,UM,Fresh,STORE01062,SS,E02,0.93,Top Up

In [24]:
def group_time(x):
    if 1 <= x <= 6:
        return 'Morning'
    elif 7 <= x <= 12:
        return 'Afternoon'
    elif 13 <= x <= 18:
        return 'Evening'
    else:
        return 'Night'

df['SHOP_HOUR_GROUP']=df['SHOP_HOUR'].apply(group_time)
df

,SHOP_WEEK,SHOP_DATE,SHOP_WEEKDAY,SHOP_HOUR,QUANTITY,PROD_CODE,PROD_CODE_10,PROD_CODE_20,PROD_CODE_30,PROD_CODE_40,...,BASKET_ID,BASKET_SIZE,BASKET_PRICE_SENSITIVITY,BASKET_DOMINANT_MISSION,STORE_CODE,STORE_FORMAT,STORE_REGION,SPEND,BASKET_TYPE,SHOP_HOUR_GROUP
0,200607,2006-04-11,Tuesday,16,1,PRD0900011,CL00033,DEP00008,G00004,D00002,...,994100000000000,L,UM,Fresh,STORE00001,LS,E02,1.05,Top Up,Evening
1,200607,2006-04-11,Tuesday,19,3,PRD0900035,CL00113,DEP00040,G00011,D00003,...,994100000000000,L,MM,Mixed,STORE00001,LS,E02,1.65,Full Shop,Night
2,200607,2006-04-14,Friday,21,1,PRD0900043,CL00148,DEP00052,G00015,D00003,...,994100000000000,L,LA,Mixed,STORE00001,LS,E02,0.71,Top Up,Night
3,200607,2006-04-14,Friday,14,1,PRD0900057,CL00107,DEP00037,G00010,D00003,...,994100000000000,L,LA,Fresh,STORE00001,LS,E02,0.46,Full Shop,Evening
4,200607,2006-04-11,Tuesday,16,1,PRD0900058,CL00020,DEP00005,G00003,D00001,...,994100000000000,L,UM,Fresh,STORE00001,LS,E02,1.87,Top Up,Evening
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270681,200819,2008-07-03,Thursday,15,3,PRD0902428,CL00222,DEP00076,G00023,D00005,...,994111700127061,L,UM,Mixed,STORE01062,SS,E02,0.39,Full Shop,Evening
270682,200819,2008-07-01,Tuesday,14,3,PRD0902348,CL00092,DEP00027,G00008,D00002,...,994111700733938,L,LA,Mixed,STORE01062,SS,E02,5.07,Top Up,Evening
270683,200819,2008-07-01,Tuesday,14,1,PRD0904799,CL00092,DEP00027,G00008,D00002,...,994111700733938,L,LA,Mixed,STORE01062,SS,E02,0.38,Top Up,Evening
270684,200819,2008-07-05,Saturday,13,1,PRD0901943,CL00043,DEP00011,G00004,D00002,...,994111700167348,M,UM,Fresh,STORE01062,SS,E02,0.41,Top Up,Evening
270685,200819,2008-07-05,Saturday,13,1,PRD0903966,CL00068,DEP00019,G00007,D00002,...,994111700167348,M,UM,Fresh,STORE01062,SS,E02,0.93,Top Up,Evening

In [27]:
df.to_csv('D:/MBB 28/Data Analysis Portofolio Project/dunhumby/retail/datasets/datasets_retail/cleaned_dunnhumby.csv', 
          index=False,
          sep=';',
          decimal=',')